### ISSUE TITLE
add suport for pg_timetable v4.6

### ISSUE THREAD

**Issue by pashagolub** [cybertec-postgresql/pg_timetable_gui#41]

**Comment by RG40** [comment]
Hi,

It's a great idea, 👍

but i see erros in log when i connect in the query like task_id that doesn't exist in chain table
 
`prepare prepst1  as SELECT
  chain_id,
  task_id,
  chain_name,
  COALESCE(run_at, '* * * * *') as run_at,
  max_instances,
  live,
  self_destruct,
  exclusive_execution,
  client_name,
  timeout,
  max_instances
FROM timetable.chain
ORDER BY chain_id`
