### ISSUE TITLE
Error when connect - Missing 2 columns in DDL timetable creation tables

### ISSUE THREAD

**Issue by jonnyforestGIS** [cybertec-postgresql/pg_timetable_gui#46]
**Backend:** 
SO: Windows 10 Entreprise
**pg_timetable version:** 
4.8.0 (Note: for now I use this version until the AntiVirus Carbon Black removes 5.0.0 as a false positive because of APC.exe)

Hi,
when we login to pg_timetable_gui for the first time give the error of missing fields in two tables:

1. timetable.chain don't find the task_id column
2. timetable.taks don't find the parent_id column

Looking at the DDL creation of the tables in the repo of the timetable these two fields are missing in the tables.

Missing task_id column
[Table timetable.chain](https://github.com/cybertec-postgresql/pg_timetable/blob/d677e0c7f30bad19ad2b42678892be9597bd655b/internal/pgengine/sql/ddl.sql#L34
)

Missing parent_id column
[Table timetable.tasks](https://github.com/cybertec-postgresql/pg_timetable/blob/d677e0c7f30bad19ad2b42678892be9597bd655b/internal/pgengine/sql/ddl.sql#L65
)

I create these two columns as bigint with sequences in the tables and apparently the interface connected successfully. But my doubt is: Are really needed these to add these columns or the columns were renamed and is that the reason for fail in the GUI?

Cheers

**Comment by pashagolub** [comment]
Hello,

thanks for your request. Seems you were using the v0.1 release which is significantly outdated. GUI app is still the work in progress so it's better to use [daily builds](https://github.com/cybertec-postgresql/pg_timetable_gui/releases/tag/daily_builds) for your tests.

I've deleted v0.1 release not to confuse people.

Regards,

Pavlo

**Comment by jonnyforestGIS** [comment]
Thank you for your feedback @pashagolub. Cheers
